### ISSUE TITLE
Fix Function Parsing

### ISSUE THREAD

**Issue by dhumm** [MitchStephan/HO-Dsl-OR#15]
We had to go off spec to get function parsing to work (specifically, we had to bound the function parameters in both the declaration and call to be bounded by parenthesis). We should fix this to make it match the "style" of the rest of the code.

**Comment by RyFry** [comment]
I attempted to change the spec to something like
`_HODOR_ funcName varName* Hodor block`
rather than having to wrap the `varName*` in parentheses, but I couldn't get that to parse either. It seems like we have to wrap `varName*` in SOMETHING to get it to parse right.

**Comment by RyFry** [comment]
I also changed the `(varName*)` to `rodoH varName* Hodor` just to see what would happen, but that didn't parse either. I thought that it had something to do with the fact that `varName` matches the regex `[A-Za-z0-9]`, which `Hodor` falls under, so anything else might do the trick. But, `!Hodor` didn't match either, which is not captured by the `varName` regex.
